INSERT INTO purse_type VALUES (1, 'WebMoney', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO purse_type VALUES (2, 'Bitcoin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO name VALUES (1, 'EUR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO name VALUES (2, 'BTC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO role VALUES (1, 'ROLE_CLIENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO person VALUES
  (1, 'ivan', 'alexandrovich', 'nahodko', 'nahodko@gmail.com', '123', '000-000-00-00', CURRENT_TIMESTAMP,
   CURRENT_TIMESTAMP, 'CLIENT');
INSERT INTO person_role VALUES (1, 1);

INSERT INTO purse VALUES (1, 'U123', 1, 1, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO purse VALUES (2, 'B456', 2, 2, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO transaction
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5, 'DEBIT', 1, 2, 'just for fun', 'SUCCESS');
INSERT INTO transaction
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6, 'CREDIT', 2, 1, 'just for fun', 'SUCCESS');